### ISSUE TITLE
Consecutive QSOs that are DUPEs cause the log loader to crash

### ISSUE THREAD

**Issue by N0SO** [N0SO/moqputils#20]
While loading 2021 log files into the database file W3LL.LOG contained consecutive QSOs that were DUPES. This was part of a multi-county line QSO with W0W where one of the 3 counties was logged twice in a row. This caused a crash:
Traceback (most recent call last):
  File "/home/pi/Projects/moqputils/logchecker/ui.py", line 150, in on_Open1_activate
    self.on_fileButton_clicked(args)  
  File "/home/pi/Projects/moqputils/logchecker/ui.py", line 197, in on_fileButton_clicked
    self.status2_text = check.processAndDisplay(self.log)
  File "/home/pi/Projects/moqputils/logchecker/runlogcheck.py", line 84, in processAndDisplay
    self.sw_replaceExisting)
  File "/home/pi/Projects/moqputils/moqputils/moqploadlogs.py", line 103, in loadToDB
    result = mydb.write_qsolist(newLogID, log['QSOLIST'])
  File "/home/pi/Projects/moqputils/moqputils/moqpdbutils.py", line 570, in write_qsolist
    qso['DUPE'] = qidlist[di-1]

Removing the duplicate QSO allowed the file to load.

See the ORIGINAL 2021 W3LL.LOG file (not the edited version in the UPLOADED folder.
[W3LL.log](https://github.com/N0SO/moqputils/files/7035225/W3LL.log)

**Comment by N0SO** [comment]
DUPES where the time didn't match the order (i.e. the times were not sequential) caused this. Solution was to:
1. Assign each QSO line a QSO ID (QID)
2. Re-order the QSOs by date/time
3. Perform QSO  DUPE check, saving the QID number as the DUPE flag (zero [0] = not a DUPE).
4. Re-order the QSOs by QID.

**Comment by N0SO** [comment]
Fixed as part of the moqpcategory-update project - included in commit  in 34e3cd4

**Comment by N0SO** [comment]
See comment above.
